In [1]:
import csv
import numpy as np
import pandas as pd
from dfs_semantics import MeaningSpace, Semantics
import dfs_semantics as dfs

In [2]:
p = ['happy(john)', 'walks(john)', 'happy(mary)', 'walks(mary)',]

In [3]:
s = Semantics(propositions=p)
print(s.space.matrix)

[[0 0 0 0]
 [0 0 0 1]
 [0 0 1 0]
 [0 0 1 1]
 [0 1 0 0]
 [0 1 0 1]
 [0 1 1 0]
 [0 1 1 1]
 [1 0 0 0]
 [1 0 0 1]
 [1 0 1 0]
 [1 0 1 1]
 [1 1 0 0]
 [1 1 0 1]
 [1 1 1 0]
 [1 1 1 1]]


## One place predicate

In [4]:
john = s.getWordSemantics('john')
mary = s.getWordSemantics('mary')
walks = s.getWordSemantics('walks')

In [5]:
y = s.setMerge(john, walks)
s.space.printSet(dfs.matrix_to_set(y))
x =s.setMerge(mary, walks)
s.space.printSet(dfs.matrix_to_set(x))
print(y.T)
print(x.T)

{'walks(john)'}
{'walks(mary)'}
[[0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1]]
[[0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]]


### Walks(john&mary)

In [6]:
walks_johnandmary = dfs.vector_and(y, x).astype(int)
walks_johnandmary.T

array([[0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1]])

In [7]:
dfs.vector_and(s.setMerge(walks, john), s.setMerge(walks, mary)).astype(int).T

array([[0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1]])

In [8]:
# walks(john&mary)
john_and_mary = s.setAnd(mary, john)
merged = s.setMerge(walks, john_and_mary)
john_and_mary.astype(int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 1],
       [0, 1, 0, 0],
       [0, 1, 0, 1],
       [0, 0, 0, 0],
       [0, 0, 1, 0],
       [1, 0, 0, 0],
       [1, 0, 1, 0],
       [0, 0, 0, 0],
       [0, 0, 1, 1],
       [1, 1, 0, 0],
       [1, 1, 1, 1]])

In [9]:
merged.astype(int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 1],
       [1, 0, 0],
       [1, 0, 1],
       [0, 0, 0],
       [0, 1, 0],
       [0, 0, 0],
       [0, 1, 0],
       [0, 0, 0],
       [0, 1, 1],
       [1, 0, 0],
       [1, 1, 1]])

Met de hand gecheckt: bovenstaande matrix bestaat uit de kolommen:
- walks(john) ^ happy(mary)
- walks(mary) ^ happy(john)
- walks(john ^ walks(mary)

## Two-place predicates

In [10]:
p = ['happy(john)', 'walks(john)', 'eat(apple, john)', 'eat(pear, john)',]
t = Semantics(propositions=p)
print(t.space.matrix)

[[0 0 0 0]
 [0 0 0 1]
 [0 0 1 0]
 [0 0 1 1]
 [0 1 0 0]
 [0 1 0 1]
 [0 1 1 0]
 [0 1 1 1]
 [1 0 0 0]
 [1 0 0 1]
 [1 0 1 0]
 [1 0 1 1]
 [1 1 0 0]
 [1 1 0 1]
 [1 1 1 0]
 [1 1 1 1]]


In [11]:
john_2 = t.getWordSemantics('john')
eat = t.getWordSemantics('eat')
apple = t.getWordSemantics('apple')
pear = t.getWordSemantics('pear')

In [12]:
john_eats_x = t.setMerge(eat, john_2)
print(john_eats_x)
t.space.printSet(dfs.matrix_to_set(john_eats_x))

[[0 0]
 [0 1]
 [1 0]
 [1 1]
 [0 0]
 [0 1]
 [1 0]
 [1 1]
 [0 0]
 [0 1]
 [1 0]
 [1 1]
 [0 0]
 [0 1]
 [1 0]
 [1 1]]
{'eat(pear, john)', 'eat(apple, john)'}


In [13]:
apple_eaten = t.setMerge(eat, apple)
print(apple_eaten.T)
t.space.printSet(dfs.matrix_to_set(apple_eaten))

[[0 0 1 1 0 0 1 1 0 0 1 1 0 0 1 1]]
{'eat(apple, john)'}


In [14]:
apple_and_pear = t.setAnd(apple, pear)
print(t.setMerge(eat, apple_and_pear).astype(int).T)
print(dfs.vector_and(t.space.matrix[:,2], t.space.matrix[:,3]).astype(int))


[[0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 1]]
[0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 1]
